eureka:
    instance:
        instance-id: ${spring.application.name}:${random.uuid}
server:
    port: 0
spring:
    application:
        name: stock-microservice
    cloud:
        config:
            profile: dev
            uri: http://localhost:8888
        vault:
            application-name: ${spring.application.name}
            authentication: TOKEN
            host: localhost
            port: 8200
            scheme: http
            token: 00000000-0000-0000-0000-000000000000
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        username: guest
